version: '3'

services:

  neo4j:
    container_name: dart_neo4j
    image: neo4j:4.0.5
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/letmein

  rabbitmq:
    container_name: dart_rabbit
    image: rabbitmq:3.8.4-management
    ports:
      - 5672:5672
      - 15672:15672

  # mongod --httpinterface
  mongodb:
    container_name: dart_mongodb
    hostname: mongodb
    image: mongo:4.2.3
    ports:
      - 27017:27017
      - 28017:28017
    environment:
      #- MONGO_INITDB_DATABASE=transport
      #- MONGO_INITDB_ROOT_USERNAME=master
      #- MONGO_INITDB_ROOT_PASSWORD=letmein
      - AUTH=no
    networks:
      - mongonet

  mongo-admin:
    container_name: dart_mongodb-admin
    depends_on:
      - mongodb
    hostname: mongo-admin
    image: mongo-express:0.54.0
    ports:
      - 8081:8081
    networks:
      - mongonet
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017

networks:
  mongonet:
    driver: bridge
